# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RealmKitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmKit', :path => '../RealmKitPod'

end
